version: '3'

services:
  mysql-local:
    image: mysql
    container_name: mysql-local
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=dbname
      - MYSQL_ROOT_PASSWORD=root
    command: --default-authentication-plugin=mysql_native_password
  vanilla-local:
    build:
      context: ./docker/vanilla
    container_name: vanilla-local
    ports:
      - 80:80
    links:
      - mysql-local
